---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: config-server
- name: bosh-cli

outputs:
- name: bosh-release

run:
  path: config-server/ci/tasks/bosh-release.sh
