---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: "2.3.1"

inputs:
- name: config-server

outputs:
- name: bosh-release

run:
  path: config-server/ci/tasks/bosh-release.sh
