---
jobs:
  - name: test-unit
    public: true
    plan:
      - {get: config-server, trigger: true}
      - task: test-unit
        file: config-server/ci/tasks/test-unit.yml

  - name: test-integration
    public: true
    plan:
      - {get: config-server, trigger: true}
      - task: test-integration
        file: config-server/ci/tasks/test-integration.yml

  - name: build
    public: true
    plan:
      - aggregate:
        - get: config-server
          passed: [test-unit, test-integration]
          trigger: true
        - get: version-semver
          params: {bump: patch}
      - {put: version-semver, params: {file: version-semver/number}}
      - aggregate:
        - task: build-linux
          file: config-server/ci/tasks/build-linux.yml
        - task: build-darwin
          file: config-server/ci/tasks/build-darwin.yml
      - aggregate:
        - {put: release-bucket-linux, params: {file: compiled-linux/config-server-*-linux-amd64}}
        - {put: release-bucket-darwin, params: {file: compiled-darwin/config-server-*-darwin-amd64}}
        - {put: config-server-promoted, params: {repository: config-server, tag: version-semver/number, tag_prefix: v}}

  - name: bump-minor
    public: true
    plan:
      - get: version-semver
        params: {bump: minor}
      - {put: version-semver, params: {file: version-semver/number}}

  - name: bump-major
    public: true
    plan:
      - get: version-semver
        params: {bump: major}
      - {put: version-semver, params: {file: version-semver/number}}

resources:
  - name: config-server
    type: git
    source:
      uri: git@github.com:cloudfoundry/config-server.git
      branch: develop
      private_key: {{concourse_github_private_key}}

  - name: config-server-promoted
    type: git
    source:
      uri: git@github.com:cloudfoundry/config-server.git
      branch: master
      private_key: {{concourse_github_private_key}}

  - name: release-bucket-linux
    type: s3
    source:
      regexp: config-server-(.*)-linux-amd64
      bucket: {{aws_s3_release_bucket}}
      region_name: {{aws_s3_release_bucket_region}}
      access_key_id: {{aws_s3_release_bucket_access_key}}
      secret_access_key: {{aws_s3_release_bucket_secret_key}}

  - name: release-bucket-darwin
    type: s3
    source:
      regexp: config-server-(.*)-darwin-amd64
      bucket: {{aws_s3_release_bucket}}
      region_name: {{aws_s3_release_bucket_region}}
      access_key_id: {{aws_s3_release_bucket_access_key}}
      secret_access_key: {{aws_s3_release_bucket_secret_key}}

  - name: version-semver
    type: semver
    source:
      initial_version: 0.0.20
      key: current-version
      bucket: {{aws_s3_release_bucket}}
      access_key_id: {{aws_s3_release_bucket_access_key}}
      secret_access_key: {{aws_s3_release_bucket_secret_key}}